### ISSUE TITLE
Unexpected key(s) in discovery.json

### ISSUE THREAD

**Issue by vladimir-yuldashev** [thecodingmachine/discovery#6]
Hey there,

I am getting an error: Unexpected key(s) in discovery.json from package fondbot/telegram: "meta"

My discovery.json:
```
{
  "FondBot\\Drivers\\Driver": [
    {
      "value": "FondBot\\Drivers\\Telegram\\TelegramDriver",
      "meta": {
        "name": "telegram"
      }
    }
  ]
}
```

I am doing the exact way as written in documentation: https://thecodingmachine.github.io/discovery/doc/discovery_schema.html

Help me please if I am wrong with something.

**Comment by moufmouf** [comment]
Hey @vladimir-yuldashev ,

The discovery.json file seems legit to me.

Could you give me more data so that I can reproduce the bug?

Is this code pushed on a GIT repo somewhere so that I can test it myself? I've been looking in https://github.com/fondbot/drivers-telegram/tree/master but there is no discovery.json file here.

Also, what version of discovery are you using?

**Comment by vladimir-yuldashev** [comment]
@moufmouf 

Yeah, example from the documentation also gives an error:

```
{
    "some_asset_type": [
        {
            "value": "some_value",
            "meta": {
                "some": "metadata",
                "more": "metadata"
            },
            "action": "add|remove",
            "priority": 99
        }
    ]
}
```

There is still no discovery.json there, I am experimenting with your package :) 
I am using ^1.1 version.

**Comment by vladimir-yuldashev** [comment]
This works:

```{
  "FondBot\\Drivers\\Driver": [
    {
      "value": "FondBot\\Drivers\\Telegram\\TelegramDriver"
    }
  ]
}```

So the problem is in `meta` key.

**Comment by moufmouf** [comment]
Ok, I just reproduced the problem. I'm looking into it.

**Comment by moufmouf** [comment]
Ok, got it! There is a typo in the documentation. The name of the key if not "meta", but "metadata".

So try this:

```json
{
  "FondBot\\Drivers\\Driver": [
    {
      "value": "FondBot\\Drivers\\Telegram\\TelegramDriver",
      "metadata": {
        "name": "telegram"
      }
    }
  ]
}
```

It should work like a charm.
I'll patch the doc now.

**Comment by vladimir-yuldashev** [comment]
Yes, `metadata` key works. Thank you! And big thanks for amazing package! Exactly, what we need for our framework.
